<?php/**
 * Ebizmarts_Autoresponder Magento JS component
 *
 * @category    Ebizmarts
 * @package     Ebizmarts_Autoresponder
 * @author      Ebizmarts Team <info@ebizmarts.com>
 * @copyright   Ebizmarts (http://ebizmarts.com)
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<?php if (!$this->dobActive()) : ?>
    <div class="box error-msg" style="padding-left:30px;">
        You must activate Show Date of Birth in System->Configuration->Customer Configuration->Name and Address Options
        to use this facility
    </div>
<?php endif; ?>